### ISSUE TITLE
[Error] Install NTFS-3G in error "undefined method `desc'"

### ISSUE THREAD

**Issue by ansonliao** [osxfuse/osxfuse#260]
Dear sir,
My Mac OSX version is EI, and I install `ntfs-3g` via command tools `brew`, the command is 
```
brew install homebrew/fuse/ntfs-3g
```

 and got the error message below:

```
Error: undefined method `desc' for Formulary::Formulae::Ntfs3g:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-fuse/Formula/ntfs-3g.rb:2:in `<class:Ntfs3g>'
/usr/local/Library/Taps/homebrew/homebrew-fuse/Formula/ntfs-3g.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:177:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:140:in `<main>'
```

Please advise how I fix the problem?

**Comment by ansonliao** [comment]
Fixed the problem after command run twice:
```
brew update
```
Please assign this issue to resolved.

**Comment by heedfull** [comment]
Worked for me too. Thanks
